apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
