name: hello-app

replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: "1.0"

service:
  port: 5678

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
